import "bootstrap/dist/css/bootstrap.min.css";
import Head from 'next/head'

export default function Home() {
  return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <h1>
            Welcome to <a href="http://nextjs.org">Next.js</a>
          </h1>

          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquid facere, ea impedit dolor sint totam fuga veritatis optio repellendus, autem expedita consequatur vel nostrum, quos suscipit cum non reiciendis a!
            
          </p>
        </main>
      </>
  );
}
